import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer'
import { useProducts } from '../hooks/use-products'


const Home = () => {
  const {data:products,error, create, remove} = useProducts();
  if(error) return <div>fail to load</div>
  if(!products) return <div>Loading...</div>
  return (
    <div className={styles.container}>
      <Head>
        <title>Hiếu Uchiha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        { 
          products.map((item:any,index:any)=> (
            <div key={index}>
                <p>{item.name}</p>
                <button onClick={() => remove(item.id)}>Delete</button>
            </div>
          ))
        }
        <button onClick={() => create({id:2,name:"Product 3"})}>Thêm</button>
      </main>
      <Footer/>
     
    </div>
  )
}

export default Home
